version: "3.7"
services:

  cxt-platform:
    image: cp-es-hackathon.artifactory.e-spirit.de/cxt-platform:2.2.1-HACKATHON
    ports:
      - "8080:8080"
    environment:
      SERVER_SERVLET_CONTEXT-PATH: /cxt-platform
      CXT_PLATFORM_INTERNAL-URL: http://localhost:8080/cxt-platform
      CXT_PLATFORM_AUTHPROVIDER: KEYCLOAK
      CXT_PLATFORM_EUREKA_PASSWORD: GEHEIM
      CXT_PLATFORM_MICROAPPS_CSP-ORIGINS: "'self' http://localhost:*"
      CXT_PLATFORM_CORS-ALLOWED-ORIGINS: "*"
      KEYCLOAK_AUTH-SERVER-URL: http://localhost:8100/auth
      KEYCLOAK_REALM: CXT
      KEYCLOAK_RESOURCE: cxt-platform
      KEYCLOAK_PUBLIC-CLIENT: "true"

  microapp-demo:
    links:
      - cxt-platform
    image: cp-es-hackathon.artifactory.e-spirit.de/cxt/microapp-demo:1.5-fs5.2.201209
    ports:
      - "8666:8666"
    environment:
      SPRING_APPLICATION_JSON: '{
          "server.port":"8666",
          "eureka.client.enabled":"true",
          "eureka.client.serviceUrl.defaultZone":"http://cxt_eureka:GEHEIM@cxt-platform:8080/cxt-platform/eureka",
          "eureka.instance.metadata-map.internalUrl":"http://microapp-demo:8666/",
          "eureka.instance.homePageUrl":"http://localhost:8666/",
          "cxt.firstspirit-connector.url":"http://cxt-platform:8080/cxt-platform/firstspirit-connector/"
          }'


