version: "3.7"
services:

  keycloak:
    image: cp-es-hackathon.artifactory.e-spirit.de/jboss/keycloak:12.0.2
    ports:
      - "8100:8080"
    volumes:
      - type: bind
        source: ./keycloak-resources
        target: /tmp/test-resources
    command: [ "-Dkeycloak.profile.feature.token_exchange=enabled",
               "-Dkeycloak.profile.feature.upload_scripts=enabled",
               "-Dkeycloak.migration.strategy=OVERWRITE_EXISTING",
               "-Dkeycloak.migration.action=import",
               "-Dkeycloak.migration.provider=singleFile",
               "-Dkeycloak.migration.file=/tmp/test-resources/realm-export.json" ]
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin

  cxt-platform:
    depends_on:
      - "keycloak"
    image: cp-es-hackathon.artifactory.e-spirit.de/cxt-platform:2.2-HACKATHON
    network_mode: "host"
    environment:
      SERVER_SERVLET_CONTEXT-PATH: /cxt-platform
      CXT_PLATFORM_INTERNAL-URL: http://localhost:8080/cxt-platform
      CXT_PLATFORM_AUTHPROVIDER: KEYCLOAK
      CXT_PLATFORM_EUREKA_PASSWORD: GEHEIM
      CXT_PLATFORM_MICROAPPS_CSP-ORIGINS: "'self' http://localhost:*"
      CXT_PLATFORM_CORS-ALLOWED-ORIGINS: "*"
      KEYCLOAK_AUTH-SERVER-URL: http://localhost:8100/auth
      KEYCLOAK_REALM: CXT
      KEYCLOAK_RESOURCE: cxt-platform
      KEYCLOAK_PUBLIC-CLIENT: "true"

  microapp-demo:
    depends_on:
      - "cxt-platform"
    image: "cp-es-hackathon.artifactory.e-spirit.de/cxt/microapp-demo:1.5-fs5.2.201209"
    network_mode: "host"
    environment:
      SPRING_APPLICATION_JSON: '{
          "server.port":"8666",
          "eureka.client.enabled":"true",
          "eureka.client.serviceUrl.defaultZone":"http://cxt_eureka:GEHEIM@localhost:8080/cxt-platform/eureka",
          "eureka.instance.metadata-map.internalUrl":"http://localhost:8666/",
          "eureka.instance.homePageUrl":"http://localhost:8666/",
          "cxt.firstspirit-connector.url":"http://localhost:8080/cxt-platform/firstspirit-connector/"
          }'


